[theme]
base = "dark"  # Указываем, что тема тёмная
backgroundColor = "#020817"
secondaryBackgroundColor = "#1F2A3D"
primaryColor = "#1F2A3D"  # Если нужно, для акцентов
textColor = "#FFFFFF"      # Контрастный цвет для текста
